# Generated by Django 6.1.1 on 2026-09-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_feedback_feedback_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='q1',
            field=models.IntegerField(verbose_name='Question #1'),
        ),
    ]
