# Generated by Django 6.1.1 on 2026-09-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_feedback_q1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='q2',
            field=models.IntegerField(verbose_name='Question #2'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q3',
            field=models.IntegerField(verbose_name='Question #3'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q4',
            field=models.IntegerField(verbose_name='Question #4'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q5',
            field=models.IntegerField(verbose_name='Question #5'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q6',
            field=models.IntegerField(verbose_name='Question #6'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q7',
            field=models.IntegerField(verbose_name='Question #7'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q8',
            field=models.IntegerField(verbose_name='Question #8'),
        ),
    ]
