# Generated by Django 6.1.1 on 2026-09-30 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_feedback_q2_alter_feedback_q3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='id',
        ),
        migrations.AddField(
            model_name='client_waiver',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q1',
            field=models.IntegerField(verbose_name='Overall_Rating'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q2',
            field=models.IntegerField(verbose_name='Service_Rating'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q3',
            field=models.IntegerField(verbose_name='Preparation_Rating'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q4',
            field=models.IntegerField(verbose_name='Professional_Rating'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q5',
            field=models.IntegerField(verbose_name='Warmth_Rating'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q6',
            field=models.IntegerField(verbose_name='Attitude_Rating'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q7',
            field=models.IntegerField(verbose_name='Consultant_Rating'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='q8',
            field=models.IntegerField(verbose_name='Experience_Rating'),
        ),
        migrations.AlterField(
            model_name='services',
            name='client_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.client_waiver'),
        ),
    ]
