# Generated by Django 6.1.1 on 2026-10-01 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_services_id_client_waiver_checked_out_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_student', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_shop_instructor', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='waxing_waiver',
            name='client_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.client_waiver'),
        ),
        migrations.AlterField(
            model_name='waxing_waiver',
            name='allergy',
            field=models.BooleanField(null=True, verbose_name='Bee Allergy'),
        ),
        migrations.AlterField(
            model_name='waxing_waiver',
            name='exposed',
            field=models.BooleanField(null=True, verbose_name='Light Exposure'),
        ),
        migrations.AlterField(
            model_name='waxing_waiver',
            name='health_issues',
            field=models.BooleanField(null=True, verbose_name='Health Conditions'),
        ),
        migrations.AlterField(
            model_name='waxing_waiver',
            name='medicine',
            field=models.BooleanField(null=True, verbose_name='Medicine'),
        ),
        migrations.AlterField(
            model_name='waxing_waiver',
            name='soap_use',
            field=models.BooleanField(null=True, verbose_name='Skin Care Use'),
        ),
    ]
